version: '3.3'
services:
  database:
    ports:
      - '1521:1521'
      - '5500:5500'
    container_name: oracle-db
    environment:
      ORACLE_SID: jiradb
      ORACLE_PDB: jiradbuser 
      ORACLE_PWD: mestre
    volumes:
      - '${PWD}/ordata:/opt/oracle/oradata'
    image: 'container-registry.oracle.com/database/enterprise:19.3.0.0'
